//
//  StateVariable.swift
//
//
//  Created by Stefan Urbanek on 19/09/2023.
//

import PoieticCore


/// Structure representing a variable in a simulation state.
///
/// The structure is analogous to an entry in a symbol table generated by the
/// planner. It provides information about where a particular simulation
/// variable can be found in the simulation state.
///
/// This structure provides information about a variable used in the simulation.
/// Variable can be built-in or computed. The computed variable is representing
/// a node in the model, typically a node with a formula.
///
public struct StateVariable: CustomStringConvertible {
    /// Reference to the variable in the simulation index.
    ///
    /// - SeeAlso: ``SimulationState``
    ///
    public let reference: SimulationState.Reference

    /// Index of a column holding variable values in the simulation result.
    ///
    /// - SeeAlso: ``SimulationResult``
    public let resultColumn: Int

    /// Internal name of the variable.
    ///
    /// - Variables representing objects: normalised name key, for example: `population_growth`.
    /// - Internal variables have format: _node type_ + _variable type_ + _object ID_,
    ///   for example: `smooth_value_10` or `flow_adjusted_24`.
    ///
    /// - Note: Internal variable names do not have to be unique within the plan, only variables
    ///   representing objects.
    ///
    public let nameKey: String
    
    /// Reference to the variable content – computational source of the variable.
    ///
    /// The variable reference is used in arithmetic expressions and might represent
    /// a built-in variable provided by the application or a value of an object.
    ///
    public enum Content: Hashable, CustomStringConvertible {
        /// The variable is represented by an object with given object ID.
        ///
        case object(ObjectID)
        
        /// The variable is a built-in variable.
        ///
        case builtin(BuiltinVariable)
        
        /// Internal state of an object.
        ///
        /// An object might have additional internal states. The case parameter
        /// is ID of an object that owns the state.
        ///
        /// Example: initial value of a delay or smooth.
        ///
        case internalState(ObjectID)
        
        /// Variable holds an estimated value – value before adjustment. For example value of a
        /// flow rate to/from a non-negative stock, as is computed from the formula, before
        /// the flow availability is computed.
        ///
        case estimated(ObjectID)
        
        public var description: String {
            switch self {
            case .object(let id): "object(\(id))"
            case .builtin(let variable): "builtin(\(variable))"
            case .internalState(let id): "internal(\(id))"
            case .estimated(let id): "estimated(\(id))"
            }
        }
    }
    
    /// Content of the state variable - whether it is an object or a builtin.
    ///
    public let content: Content
    
    // TODO: [REFACTORING] This is used only in simulation result view and it is somewhat under-specified and unclear. Reconsider.
    /// ID of a simulation node that the variable represents, if the variable
    /// represents a node.
    ///
    /// ID is `nil` when the variable is a built-in variable or an internal
    /// state variable.
    ///
    /// Each object can be represented by only one state variable.
    ///
    public var objectID: ObjectID? {
        switch content {
        case .builtin(_): nil
        case .object(let id): id
        case .internalState(_): nil
        case .estimated(let id): id
        }
    }
    
    public var description: String {
        "\(reference)[\(nameKey),\(content),\(resultColumn)]"
    }
    
    internal init(reference: SimulationState.Reference,
                  resultColumn: Int,
                  nameKey: String,
                  content: Content) {
        self.reference = reference
        self.resultColumn = resultColumn
        self.nameKey = nameKey
        self.content = content
    }
    
    internal init(reference: SimulationState.Reference,
                  resultColumn: Int,
                  builtin: BuiltinVariable) {
        self.reference = reference
        self.resultColumn = resultColumn
        self.nameKey = builtin.normalizedKey
        self.content = .builtin(builtin)
    }
}

